version: '3'
services:
  es01:
    image: elasticsearch:${STACK_VERSION}
    container_name: ${ES_CONTAINER_NAME_1}
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./es/plugins:/usr/share/elasticsearch/plugins
      - ./es01/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es01/data:/usr/share/elasticsearch/data # 數據文件掛載
      - ./es01/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
  es02:
    image: elasticsearch:${STACK_VERSION}
    container_name: ${ES_CONTAINER_NAME_2}
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./es/plugins:/usr/share/elasticsearch/plugins
      - ./es02/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es02/data:/usr/share/elasticsearch/data:rw # 數據文件掛載
      - ./es02/logs:/usr/share/elasticsearch/logs:rw
    depends_on:
      - es01
  es03:
    image: elasticsearch:${STACK_VERSION}
    container_name: ${ES_CONTAINER_NAME_3}
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./es/plugins:/usr/share/elasticsearch/plugins
      - ./es03/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./es03/data:/usr/share/elasticsearch/data:rw # 數據文件掛載
      - ./es03/logs:/usr/share/elasticsearch/logs:rw
    depends_on:
      - es01
  kibana:
    image: kibana:7.13.3
    container_name: kibana
    depends_on:
      - es01 # kibana在elasticsearch啟動之後再啟動
      - es02
      - es03
    environment:
      ELASTICSEARCH_HOSTS: http://es01:9200 # 設置訪問elasticsearch的地址
      I18N_LOCALE: zh-CN
    ports:
      - 5601:5601
